spring:
  datasource:
    url: jdbc:mysql://101.132.142.119:3306/rocketapi?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 5200
    driver-class-name: com.mysql.cj.jdbc.Driver
