server:
  port: 8081

dubbo:
  application:
    # 当前应用名字
    name: spring-boot-maven-dubbo-provider
    logger: slf4j
  scan:
    # 扫描指定包下服务
    base-packages: com.snow.service
  protocol:
    name: tri
    port: -1
  registry:
    # 注册中心地址
    address: zookeeper://127.0.0.1:2181