magic-api:
  #UI鉴权登录
  security:
    username: admin # 登录用的用户名
    password: admin # 登录用的密码
  #配置web页面入口
  web: /magic/web
  resource:
    #配置文件存储位置。当以classpath开头时，为只读模式
    #mac用户请改为可读写的目录
    #如果不想存到文件中，可以参考配置将接口信息存到数据库、Redis中（或自定义）
    type: file # 此项默认值是file，可省略
    location: data/magic-api
  #接口前缀，可以不配置
  prefix: /api/v1
  swagger:
    version: 1.0
    description: MagicAPI 接口信息
    title: MagicAPI Swagger Docs
    name: MagicAPI 接口
    location: /v2/api-docs/magic-api/swagger2.json

spring:
  datasource:
    url: jdbc:mysql://101.132.142.119:3306/magicapi?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 5200
    driver-class-name: com.mysql.cj.jdbc.Driver
